version: '3'
services:
  mysql-spe-service:
    image: mysql
    container_name: mysql-spe-services
    restart: always
    networks:
      - spe-network
    environment:
      MYSQL_DATABASE: "ticketresolver"
      MYSQL_ROOT_PASSWORD: "Abcd@1234"
      MYSQL_ROOT_HOST: "spe-project"
    ports:
      - "3307:3306"
    volumes:
      - "~/spe-dp:/var/lib/mysql"

  ticketresolver_backend_Container:
    image: "sarthakharne2262/ticketresolver-backend:latest"
    container_name: ticketresolver_backend_Container
    restart: always
    networks:
      - spe-network
    # environment:
    #   MYSQL_URL: jdbc:mysql://spe-project:3307/ticketresolver?createDatabaseIfNotExist=true&swapsieDevops?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC
    #   MYSQL_NAME: spe-project
    #   MYSQL_PASSWORD: Abcd@1234
    ports:
      - "8081:8081"
    depends_on:
      - mysql-spe-service

  ticketresolver_frontend_Container:
    image: "sarthakharne2262/ticketresolver_frontend:latest"
    container_name: ticketresolver_frontend_Container
    restart: always
    networks:
      - spe-network
    ports:
      - "3000:3000"
    depends_on:
      - ticketresolver_backend_Container
    
networks:
  spe-network:
    driver: bridge

volumes:
  spe-dp: